### PR TITLE
Add waiting_room parameter to meeting_create

### PR DESCRIPTION
**Pull request by KatherineMuedas**
Adds the waiting_room parameter (boolean) to meeting_create to enable the [Waiting Room feature](https://support.zoom.us/hc/en-us/articles/115000332726-Waiting-Room).

### CODE REVIEW

**Comment by KatherineMuedas** [comment]
Hello @kyleboe, Could you review this PR when you have a chance? 
Let me know if you have any questions
Thank you!

**Review by kyleboe — APPROVED** [review]
LGTM! 👍 Thanks for the contribution!

**Comment by KatherineMuedas** [comment]
Thank you @kyleboe !
When is the next release coming up?

**Comment by kyleboe** [comment]
@KatherineMuedas Sorry for the delayed response! Just pushed up a new version now.

**Pull request merged**
